### ISSUE TITLE
[FEATURE] #19 판매글 작성 페이지 정적 UI 퍼블리싱

### ISSUE THREAD

**Issue by f0rever0** [Team-PocaLink/Pocalink-Client#19]
## 🌴 작업 브랜치 
feature/#19

## 💼 TASK 개요 
판매글 작성 페이지 정적 UI 퍼블리싱입니다.
![image](https://user-images.githubusercontent.com/62867581/210162832-d35ec369-a138-4b6d-ab23-8f38d4090e86.png)

## ✅ TODO 및 진행현황 

- [ ] 판매글 작성 페이지 정적 UI 퍼블리싱

**Comment by YOOJS1205** [comment]
우영이형 빠이팅
