### ISSUE TITLE
[FEATURE] #20 판매글 인증사진 가이드 페이지 정적 UI 퍼블리싱

### ISSUE THREAD

**Issue by f0rever0** [Team-PocaLink/Pocalink-Client#20]
## 🌴 작업 브랜치 
feature/#20

## 💼 TASK 개요 
판매글 인증사진 가이드 페이지 정적 UI 퍼블리싱입니다.
![image](https://user-images.githubusercontent.com/62867581/210174222-a7e47b82-baab-4ba1-927d-2d7d2cab0fb1.png)

## ✅ TODO 및 진행현황

- [ ] 판매글 인증사진 가이드 페이지 정적 UI 퍼블리싱

**Comment by YOOJS1205** [comment]
우영이형 빠이팅
