### ISSUE TITLE
[FEATURE] #21 판매글 가격옵션 설정 페이지 정적 UI 퍼블리싱

### ISSUE THREAD

**Issue by f0rever0** [Team-PocaLink/Pocalink-Client#21]
## 🌴 작업 브랜치 
feature/#21

## 💼 TASK 개요 
판매글 가격옵션 설정 페이지 정적 UI 퍼블리싱입니다.
![image](https://user-images.githubusercontent.com/62867581/210162809-8401c0be-5123-4f13-913a-fe05411c2ec2.png)

## ✅ TODO 및 진행현황 

- [ ] 판매글 가격옵션 설정 페이지 정적 UI 퍼블리싱

**Comment by YOOJS1205** [comment]
우영이형 빠이팅
